from comtypes.hresult import *

E_HANDLE = 2147942406
E_ACCESSDENIED = 0x80070005
ERROR_FILE_NOT_FOUND = 2

SYN_OK = 0
SYN_FALSE = 0
SYN_TRUE = 1

SYNE_HANDLE = E_HANDLE
SYNE_FAIL = E_FAIL
SYNE_INVALIDARG = E_INVALIDARG
SYNE_OUTOFMEMORY = E_OUTOFMEMORY
SYNE_ACCESSDENIED = E_ACCESSDENIED
SYNE_NOTIMPL = E_NOTIMPL
SYNE_SEQUENCE = E_UNEXPECTED

SYNE_NOTFOUND = MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WIN32, ERROR_FILE_NOT_FOUND)
